name: Waka Readme

on:
  push:
    branches:
      - develop
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Update README.md with WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@v4
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
